apiVersion: v1
kind: Template
labels:
  limit-and-quota-tier: large
metadata:
  creationTimestamp: null
  name: project-request
objects:
- apiVersion: v1
  kind: LimitRange
  metadata:
    labels:
      quota-tier: large
    name: limitrange-large
  spec:
    limits:
    - default:
        cpu: 600m
        memory: 6Gi
      defaultRequest:
        cpu: 100m
        memory: 512Mi
      max:
        cpu: 4000m
        memory: 16Gi
      min:
        cpu: 50m
        memory: 16Mi
      type: Container
      maxLimitRequestRatio:
        cpu: "80"
        memory: "1024"
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    labels:
      quota-tier: large
    name: quota-large
  spec:
    hard:
      limits.cpu: "75"
      limits.memory: 384Gi
      pods: "500"
      requests.cpu: "50"
      requests.memory: 128Gi
      requests.storage: 300Gi
